import { NextResponse } from 'next/server';
import connectDB from '@/lib/db';
import Document from '@/models/Document';
import { writeFile, mkdir } from 'fs/promises';
import { readdir } from 'fs/promises';
import path from 'path';
import { v4 as uuidv4 } from 'uuid';
import { requireAdmin } from '@/lib/auth';
import { getErrorMessage } from '@/lib/errors';
import { ensureDefaultCategories, inferCategoryNameFromFile } from '@/lib/categories';

// Maximum file size in bytes (500 MB by default, configurable via env var)
const MAX_FILE_SIZE = parseInt(process.env.MAX_DOCUMENT_SIZE_MB || '500', 10) * 1024 * 1024;
const ALLOWED_EXTENSIONS = new Set(['.pdf', '.doc', '.docx', '.xls', '.xlsx', '.ppt', '.pptx']);
const ALLOWED_TYPES = new Set([
  'application/pdf',
  'application/msword',
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  'application/vnd.ms-excel',
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  'application/vnd.ms-powerpoint',
  'application/vnd.openxmlformats-officedocument.presentationml.presentation',
]);

export async function GET(req: Request) {
  try {
    await connectDB();
    await seedExistingPolicyFiles();
    const { searchParams } = new URL(req.url);
    const categoryId = searchParams.get('categoryId');
    
    let query = {};
    if (categoryId && categoryId !== 'all') {
      query = { categoryId };
    }

    const documents = await Document.find(query).populate('categoryId').sort({ createdAt: -1 });
    return NextResponse.json(documents);
  } catch (error: unknown) {
    return NextResponse.json({ message: getErrorMessage(error, 'Unable to load documents') }, { status: 500 });
  }
}

async function seedExistingPolicyFiles() {
  const uploadDir = path.join(process.cwd(), 'public', 'uploads', 'Policies');
  let files: string[] = [];

  try {
    files = await readdir(uploadDir);
  } catch {
    return;
  }

  const categories = await ensureDefaultCategories();
  const categoryByName = new Map(categories.map((category) => [category.name, category._id]));

  await Promise.all(
    files
      .filter((fileName) => ALLOWED_EXTENSIONS.has(path.extname(fileName).toLowerCase()))
      .map(async (fileName) => {
        const fileUrl = `/uploads/Policies/${fileName}`;
        const exists = await Document.exists({ fileUrl });
        if (exists) return;

        const categoryName = inferCategoryNameFromFile(fileName);
        const categoryId = categoryByName.get(categoryName) || categoryByName.get('COMPANY POLICIES');
        if (!categoryId) return;

        await Document.create({
          title: path.basename(fileName, path.extname(fileName)).replace(/[_-]+/g, ' ').replace(/\s+/g, ' ').trim(),
          fileUrl,
          categoryId,
        });
      })
  );
}

export async function POST(req: Request) {
  try {
    const { error } = requireAdmin(req);
    if (error) return NextResponse.json({ message: error.message }, { status: error.status });

    await connectDB();
    const formData = await req.formData();
    const file = formData.get('file') as File;
    const title = String(formData.get('title') || '').trim();
    const categoryId = formData.get('categoryId') as string;

    if (!file || !title || !categoryId) {
      return NextResponse.json({ message: 'Missing fields' }, { status: 400 });
    }

    if (file.size > MAX_FILE_SIZE) {
      const maxSizeMB = parseInt(process.env.MAX_DOCUMENT_SIZE_MB || '500', 10);
      return NextResponse.json({ message: `File size must be ${maxSizeMB} MB or less` }, { status: 400 });
    }

    const originalName = file.name || 'document';
    const extension = path.extname(originalName).toLowerCase();
    if (!ALLOWED_EXTENSIONS.has(extension) || (file.type && !ALLOWED_TYPES.has(file.type))) {
      return NextResponse.json({ message: 'Upload a PDF, Word, Excel, or PowerPoint document' }, { status: 400 });
    }

    const bytes = await file.arrayBuffer();
    const buffer = Buffer.from(bytes);

    const safeBaseName = path
      .basename(originalName, extension)
      .replace(/[^a-z0-9-_]+/gi, '-')
      .replace(/-+/g, '-')
      .replace(/^-|-$/g, '')
      .slice(0, 80) || 'document';
    const fileName = `${uuidv4()}-${safeBaseName}${extension}`;
    const uploadDir = path.join(process.cwd(), 'public', 'uploads', 'Policies');

    await mkdir(uploadDir, { recursive: true });

    const filePath = path.join(uploadDir, fileName);
    await writeFile(filePath, buffer);

    const fileUrl = `/uploads/Policies/${fileName}`;

    const newDocument = new Document({
      title,
      fileUrl,
      categoryId,
      // thumbnailUrl will be set later or generated by frontend
    });

    await newDocument.save();
    await newDocument.populate('categoryId');
    return NextResponse.json(newDocument, { status: 201 });
  } catch (error: unknown) {
    console.error('Upload error:', error);
    return NextResponse.json({ message: getErrorMessage(error, 'Unable to upload document') }, { status: 500 });
  }
}
